name: Merge Bot

on:
  pull_request:
    types: [ opened , reopened , labeled , unlabeled , ready_for_review ,  enhancement, Version Upgrade ]

  pull_request_review:
    types: [ submitted ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge PR
        uses: squalrus/merge-bot@v0.1.0
        with:
          GITHUB_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
          test: true
          reviewers: true
          labels: ready, merge
          blocking_labels: do not merge
          checks_enabled: true
          method: squash
          delete_source_branch: true
          merge_message: "Merged by Merge Bot"
          merge_message_regex: "Merged by Merge Bot"

