name: Check pull request 👀.

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - name: Decode google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.APP_GOOGLE_JSON }}
        run: echo $GOOGLE_SERVICES_JSON > ./bitapp/google-services.json
      - name: Creating Local.Properties
        env:
          FIREBASE_WEB_CLIENT_ID: ${{ secrets.FIREBASE_WEB_CLIENT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "firebaseWebClient=${FIREBASE_WEB_CLIENT_ID}" >> ./local.properties
          echo "apiKey=${GEMINI_API_KEY}" >> ./local.properties
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Assemble Debug APK
        run: ./gradlew :bitapp:assembleDebug --stacktrace